# sudo: false
language: node_js
node_js:
- lts/*
# cache:
#   directories:
#   - node_modules
# branches:
#   only:
#   - master
# notifications:
#   email: false
before_script:
- echo "process npm prune"
- npm prune
script:
- npm run build
# after_success:
# - bash ./.bin/deploy.sh
before_deploy:
- echo "before_deploy"

deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  github_token: gh-pages # Set in travis-ci.org dashboard
  # on:
  #   all_branches: true

after_deploy:
- echo "after_deploy"