# sudo: false
language: node_js
node_js:
- lts/*
# cache:
#   directories:
#   - node_modules
# branches:
#   only:
#   - master
# notifications:
#   email: false
before_script:
- npm prune
script:
- npm run build

deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master